Waiting room queue
software-students-fall2021/project-setup-foodwithfriends pull request #142
Opened 2021-11-23 05:01 UTC by Golemwardox

This task is part of User Story #75...

2021-11-27 00:21 UTC, yunko1803 requested changes
Slight issues

2021-11-27 00:21 UTC, yunko1803 commented on back-end/app.js
> +  console.log("HELLO")
Delete

2021-11-27 00:21 UTC, yunko1803 commented on back-end/app.js
> +    // User.find({ _id: friends[0] }, (err, doc) => {
delete comment codes if these are not used

2021-11-27 00:21 UTC, yunko1803 commented on back-end/app.js
> +    User.find({ _id: doc.friends }, (err, userDoc) => {
it's asking id, but why is it doc.friends?
Shouldn't it be similar to doc.id?

2021-11-28 04:20 UTC, Jen-Lopez commented
btw, once #144 is pushed to master, the way the groupid/invitecode is used will change so I'd update the code accordingly.

2021-12-03 17:34 UTC, thomastai1666 approved these changes
Just a couple of suggestions but looks good!

2021-12-03 17:34 UTC, thomastai1666 commented on front-end/src/pages/Wait.jsx
> +//import { Link } from "react-router-dom";
```suggestion
```

2021-12-03 17:34 UTC, thomastai1666 commented on back-end/routes/wait.js
> +        console.log("Something wrong when finding the data");
```suggestion
        console.log("Something wrong when finding the data");
        res.status(500);
        res.send(err);
        return;
```

2021-12-03 17:34 UTC, thomastai1666 commented on front-end/src/pages/Wait.jsx
> +        if (response.num_users == response.tot_users) {
```suggestion
        if (response.num_users >= response.tot_users) {
```
Just in case someone has over the number of users we should redirect them anyways

2021-12-03 17:34 UTC, thomastai1666 commented on front-end/src/pages/Wait.jsx
> +          window.location.href = "/win";
```suggestion
          window.location.href = "/cuisine";
```

2021-12-03 17:42 UTC, thomastai1666 commented on front-end/src/pages/Wait.jsx
> +  const [groupId, setName] = React.useState("b6034"); //THIS IS TEMPORARY JUST FOR NOW
```suggestion
  const [groupId, ] = React.useState("b6034"); //THIS IS TEMPORARY JUST FOR NOW
```
This should hopefully fix the failing test on circleCI!

2021-12-03 18:03 UTC, thomastai1666 approved these changes

2021-12-03 18:39 UTC, Jen-Lopez commented
I realized that maybe there should be another temp field in the group object dedicated for the waiting room cause it seems to work for the first waiting room since the users would be there already. But when I vote on a cuisine, because the # of people in the "friends" array would already be equal to the # of users specified, it'll just skip the room...

2021-12-05 20:45 UTC, merged