Winning cuisine route
software-students-fall2021/project-setup-foodwithfriends pull request #167
Opened 2021-12-08 03:50 UTC by psc358

Added route to publish winning cuisine to database

2021-12-08 03:52 UTC, psc358 commented
this is a draft, still have to complete

2021-12-09 03:01 UTC, yunko1803 reviewed
Slight issue

2021-12-10 17:30 UTC, Jen-Lopez requested changes

2021-12-10 17:30 UTC, Jen-Lopez commented on back-end/routes/win.js
> +    Group.findOne({groupId: groupId}, (err, doc) => {
`groupId` -> `groupID`

2021-12-10 17:30 UTC, Jen-Lopez commented on back-end/routes/win.js
> +        const count = doc.selectedCuisines.find((selectedCuisine) => {return cuisine == selectedCuisine.cuisine});
I don't think this line is needed, the `if (count)` too.

2021-12-10 17:30 UTC, Jen-Lopez commented on back-end/routes/win.js
> +            Group.updateOne({groupId: groupId}, {
Instead of doing another Group Query (cause you already have the group obj already), you could replace it with: 

`doc.winningCuisine = finalCuisine;
doc.save();`

This way, it'll take less time since you only have to do one search

2021-12-10 17:30 UTC, Jen-Lopez commented on back-end/routes/win.js
> +            selectedCuisinesList.forEach((selectedCuisine, index) => {
since you're not using the index, I would just leave it at `selectedCuisine =>`

2021-12-10 17:30 UTC, Jen-Lopez commented on front-end/src/pages/WinningCuisine.jsx
> +  // "Indian" vs "indian" --> Figure out where this bug is
delete comments. Also this is fixed in the waitingRoom branch!

2021-12-11 02:44 UTC, thomastai1666 commented on back-end/routes/win.js
> +        doc.save;
should this be a function? saw this differed from what @Jen-Lopez suggested

2021-12-11 03:49 UTC, Jen-Lopez submitted a review, later dismissed

2021-12-11 03:49 UTC, thomastai1666 approved these changes

2021-12-11 03:51 UTC, Golemwardox approved these changes

2021-12-11 03:51 UTC, merged