#61: Create restaurant details page
software-students-fall2021/project-setup-foodwithfriends pull request #87
Opened 2021-11-02 01:19 UTC by thomastai1666

2021-11-02 02:47 UTC, Jen-Lopez requested changes
Just a minor fix!

2021-11-02 02:47 UTC, Jen-Lopez commented on front-end/src/pages/RestaurantDetails.css
> +  width: 100%;
When you view the page on mobile (when you navigate from home -> restaurant details), it seems like the page overflows. Changing `width` to `min-width` seems to solve the issue though. 

**BEFORE**
<img width="568" alt="before" src="https://user-images.githubusercontent.com/21044058/139778327-4fd083dd-43e8-4e41-bebd-874d781687f0.png">

**AFTER**
<img width="443" alt="after" src="https://user-images.githubusercontent.com/21044058/139778328-1a908527-0c67-4f02-b725-0b7a079211d6.png">

2021-11-02 02:54 UTC, thomastai1666 commented on front-end/src/pages/RestaurantDetails.css
> +  width: 100%;
Thank you, that looks so much better! 
```suggestion
  min-width: 100%;
```

2021-11-02 02:56 UTC, Jen-Lopez approved these changes

2021-11-06 20:20 UTC, Golemwardox approved these changes
LGTM.

2021-11-06 20:21 UTC, merged